# Tf 2.x low level API

In [ ]:
import tensorflow as tf

In [ ]:
# What is keras? is it High level API or Low level?

## High level API 

## tensor constant

### Tensor: Multi dim arrays

In [ ]:
const = tf.constant(43)

In [ ]:
const

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [ ]:
const.numpy()


43

In [ ]:
## specify the datatype
const = tf.constant(43, dtype=tf.int64)
const

<tf.Tensor: shape=(), dtype=int64, numpy=43>

In [ ]:
const_mat = tf.constant([[4,2],[9,5]])
const_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [9, 5]], dtype=int32)>

In [ ]:
const_mat.shape

TensorShape([2, 2])

In [ ]:
const_mat.dtype

tf.int32

`observe: Increase the no. hidden layers and observe what happens to size of the model that you save.

Query: Before and after training will the model size will remain same or increase or decrease? ==> remains same`

## Commonly used method

In [ ]:
tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
5 * tf.ones(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

## add operations

In [ ]:
const1 = tf.constant([[11,3,4],[3,4,5]])
const2 = tf.constant([[7,9,5],[3,4,5]])

In [ ]:
result = tf.add(const1, const2)
result

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18, 12,  9],
       [ 6,  8, 10]], dtype=int32)>

In [ ]:
const1 + const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18, 12,  9],
       [ 6,  8, 10]], dtype=int32)>

## Random const

In [ ]:
x = tf.random.normal(shape=(2,2), mean=0, stddev=1.0)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.06385966, -1.2362483 ],
       [-0.3649998 , -0.83387613]], dtype=float32)>

In [ ]:
x = tf.random.uniform(shape=(2,2), minval=0, maxval=10)
x

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[3.2337928, 6.402439 ],
       [9.346653 , 2.2888386]], dtype=float32)>

In [ ]:
x = tf.random.uniform(shape=(2,2), minval=0, maxval=10, dtype=tf.int32)
x

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[9, 8],
       [4, 4]], dtype=int32)>

## Variables



In [ ]:
var1 = tf.Variable(45)

var2 = tf.Variable([[4,2],[9,5]])

In [ ]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=45>

In [ ]:
var1.numpy()

45

In [ ]:
var1 = tf.Variable(45.4)
var1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=45.4>

In [ ]:
var1 = tf.Variable(45.4, dtype=tf.float16)
var1

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=45.4>

reassign a variable, var.assign()

In [ ]:
var1 = tf.Variable(45.4, dtype=tf.float16)

In [ ]:
var1.assign(99)
var1

<tf.Variable 'Variable:0' shape=() dtype=float16, numpy=99.0>

### reshaping operation

In [ ]:
tensor = tf.Variable([[[10, 11, 12], [13, 15, 18]],[[10, 11, 12], [13, 15, 18]]])
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [ ]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
reshape_val = tf.reshape(tensor, [2,6])
reshape_val

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 11, 12, 13, 15, 18],
       [10, 11, 12, 13, 15, 18]], dtype=int32)>

In [ ]:
reshape_val = tf.reshape(tensor, [1,12])
reshape_val

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[10, 11, 12, 13, 15, 18, 10, 11, 12, 13, 15, 18]], dtype=int32)>

## Rank of tensor

no of dimensions, 

In [ ]:
tf.rank(reshape_val)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [ ]:
tensor[0, 1, 1]

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
tensor[0,:,1:]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [15, 18]], dtype=int32)>

## more mathematical operations

In [ ]:
a = tf.random.normal((2,2))
b = tf.random.normal((2,2))


c = a + b

In [ ]:
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.2585579 ,  2.3138201 ],
       [-1.5514584 ,  0.21320283]], dtype=float32)>

In [ ]:
tf.square(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.583968  , 5.3537636 ],
       [2.407023  , 0.04545545]], dtype=float32)>

In [ ]:
tf.exp(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 3.5203412 , 10.112984  ],
       [ 0.21193866,  1.2376357 ]], dtype=float32)>

In [ ]:
# Element wise multiplication - 
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 15, 18]],

       [[10, 11, 12],
        [13, 15, 18]]], dtype=int32)>

In [ ]:
tensor * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[100, 121, 144],
        [169, 225, 324]],

       [[100, 121, 144],
        [169, 225, 324]]], dtype=int32)>

## Boradcasting in Tensorflow -


In [ ]:
scaler = 4
scaler * tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[40, 44, 48],
        [52, 60, 72]],

       [[40, 44, 48],
        [52, 60, 72]]], dtype=int32)>

In [ ]:
scaler + tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[14, 15, 16],
        [17, 19, 22]],

       [[14, 15, 16],
        [17, 19, 22]]], dtype=int32)>

In [ ]:
scaler - tensor


<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ -6,  -7,  -8],
        [ -9, -11, -14]],

       [[ -6,  -7,  -8],
        [ -9, -11, -14]]], dtype=int32)>

# Matrix multiplication

In [ ]:
mat_u = tf.constant([[6,7,7]])
mat_v = tf.constant([[3,4,3]])

In [ ]:
mat_u.shape

TensorShape([1, 3])

In [ ]:
mat_v.shape

TensorShape([1, 3])

In [ ]:
tf.transpose(mat_v).shape

TensorShape([3, 1])

In [ ]:
mat_u.numpy()

array([[6, 7, 7]], dtype=int32)

In [ ]:
tf.transpose(mat_v).numpy()

array([[3],
       [4],
       [3]], dtype=int32)

In [ ]:
tf.matmul(mat_u, tf.transpose(mat_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[67]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(mat_v), mat_u)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 21, 21],
       [24, 28, 28],
       [18, 21, 21]], dtype=int32)>

In [ ]:
tf.transpose(mat_v) @ mat_u ### <<< Matrix mul

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 21, 21],
       [24, 28, 28],
       [18, 21, 21]], dtype=int32)>

In [ ]:
mat_u @ tf.transpose(mat_v) ### <<< Matrix mul


<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[67]], dtype=int32)>

In [ ]:
mat_u * mat_v # element wise multiplication

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[18, 28, 21]], dtype=int32)>

## Casting method in tensorflow to change the datatype

In [ ]:
tf.cast(mat_u, dtype=tf.int16) ### < can be utilized in quantization

<tf.Tensor: shape=(1, 3), dtype=int16, numpy=array([[6, 7, 7]], dtype=int16)>

In [ ]:
tf.cast(tf.constant(444.1324), dtype=tf.int32)

<tf.Tensor: shape=(), dtype=int32, numpy=444>

## Ragged tensors
nested variable length arrays

In [ ]:
ragged = tf.ragged.constant([[1,2,3,4,5], [], [1,2,3]])

In [ ]:
# ragged = tf.constant([[1,2,3,4,5], [], [1,2,3]])


In [ ]:
ragged.shape

TensorShape([3, None])

In [ ]:
ragged[0, :].shape

TensorShape([5])

In [ ]:
ragged[1, :].shape


TensorShape([0])

In [ ]:
ragged[2, :].shape


TensorShape([3])

## Squared difference of tensors

In [ ]:
varx = [1,2,3,4,5,6]
vary = 2

tf.math.squared_difference(varx, vary)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 1,  0,  1,  4,  9, 16], dtype=int32)>

In [ ]:
pred = [1,2,3,4,5,6]
actual = [1,1,1,1,1,1]

tf.math.squared_difference(pred, actual)

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25], dtype=int32)>

## calculate mean

In [ ]:
num = tf.constant([[1,2],[3,4]], dtype=tf.float32)
num

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
tf.reduce_mean(num)

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [ ]:
tf.reduce_mean(num, axis=0) # row wise mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [ ]:
tf.reduce_mean(num, axis=1) # col wise mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [ ]:
tf.reduce_mean(num, axis=1, keepdims=True) # col wise mean

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.5],
       [3.5]], dtype=float32)>